### ISSUE TITLE
Recommendations for chronic two-photon recordings

### ISSUE THREAD

**Issue by neuroczy** [AllenInstitute/deepinterpolation#4]
Hello there,

I was wondering if you have any recommendations for model training for chronic 2P datasets of calcium activity? Would a single model be robust against chronic effects such as photobleaching, changes in laser power or PMT gain, and variable intrinsic brightness across different imaging regions?  Or would I have to retrain the model for each session and change in conditions?

I look forward to your reply, thanks!

**Comment by jeromelecoq** [comment]
Hello,

Thanks for reaching out. 
This is something we are working on now to provide a little more details and guidance. 

The current paper showcases 2 trained networks in 2p. We found that those generalized well through our database (many different regions/depths). They were trained across several hundreds movies so they were designed to do so. Our data collection at the Allen is reasonably standardized so that could be a factor to consider in your case. One of our published videos shows how the same network performs across 4 different movies with quite a range of different conditions.

**Comment by neuroczy** [comment]
Thanks, I'll keep that in mind!
